import type { AddProtocolAction } from 'maplibre-gl';
import {
  BUILDING_TILE_COVERAGE,
  BUILDING_TILE_ZOOM,
} from '@/app/building-tiles-coverage';

/**
 * One building source for the whole map, stitched from two tilesets.
 *
 * Inside the coverage rectangle the tiles are the game's own, generated by
 * scripts/build-building-tiles.mjs from OSM footprints and USGS 3DEP LiDAR
 * (public/buildings/14/{x}/{y}.pbf), so every building rises to its measured
 * roof height instead of OpenStreetMap's guess. Everywhere else the request
 * falls through to the OpenFreeMap tile the base style already downloads,
 * with every layer but `building` stripped out, so the goose still meets
 * walls on a flight across town.
 *
 * Both halves share the `building` source layer and OpenMapTiles' property
 * names (render_height, render_min_height), which is what the style
 * expressions and the engine's collider scan already read. A protocol keeps
 * the stitching invisible: the map sees one vector source with one tile
 * template, and the engine keeps finding buildings by the fill-extrusion
 * layer's source exactly as before.
 */
export const BUILDING_TILE_PROTOCOL = 'wmug-buildings';

export const BUILDING_TILE_TEMPLATE = `${BUILDING_TILE_PROTOCOL}://tile/{z}/{x}/{y}`;

/** The source-layer name shared by both tilesets. */
export const BUILDING_SOURCE_LAYER = 'building';

let osmBuildingTileTemplate: string | null = null;

/**
 * Remember the OpenFreeMap tile template (from the base style's TileJSON)
 * so the protocol can fetch buildings outside the LiDAR coverage from it.
 */
export const setOsmBuildingTileTemplate = (template: string | null) => {
  osmBuildingTileTemplate = template;
};

export const inBuildingTileCoverage = (zoom: number, x: number, y: number) =>
  zoom === BUILDING_TILE_ZOOM &&
  x >= BUILDING_TILE_COVERAGE.minX &&
  x <= BUILDING_TILE_COVERAGE.maxX &&
  y >= BUILDING_TILE_COVERAGE.minY &&
  y <= BUILDING_TILE_COVERAGE.maxY;

const readVarint = (bytes: Uint8Array, position: number): [number, number] => {
  let value = 0;
  let shift = 0;
  let cursor = position;
  for (;;) {
    if (cursor >= bytes.length) throw new Error('Truncated vector tile.');
    const byte = bytes[cursor];
    cursor += 1;
    // Multiplying instead of shifting keeps lengths above 2^31 exact.
    value += (byte & 0x7f) * 2 ** shift;
    if (byte < 0x80) return [value, cursor];
    shift += 7;
    if (shift > 63) throw new Error('Malformed varint in vector tile.');
  }
};

/** Advance past one protobuf field body of the given wire type. */
const skipField = (bytes: Uint8Array, wireType: number, position: number) => {
  switch (wireType) {
    case 0:
      return readVarint(bytes, position)[1];
    case 1:
      return position + 8;
    case 2: {
      const [length, bodyStart] = readVarint(bytes, position);
      return bodyStart + length;
    }
    case 5:
      return position + 4;
    default:
      throw new Error(`Unsupported wire type ${wireType} in vector tile.`);
  }
};

const utf8 = new TextDecoder();

/** The `name` (field 1) of a Mapbox Vector Tile layer message. */
const layerName = (bytes: Uint8Array, start: number, end: number) => {
  let cursor = start;
  while (cursor < end) {
    const [tag, afterTag] = readVarint(bytes, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag & 7;
    if (field === 1 && wireType === 2) {
      const [length, bodyStart] = readVarint(bytes, afterTag);
      return utf8.decode(bytes.subarray(bodyStart, bodyStart + length));
    }
    cursor = skipField(bytes, wireType, afterTag);
  }
  return null;
};

/**
 * Keep only the `building` layer of a Mapbox Vector Tile. A tile is a flat
 * list of layer messages (field 3), so this copies the matching messages
 * byte for byte and never has to decode features.
 */
export const extractBuildingLayer = (tile: ArrayBuffer): ArrayBuffer => {
  const bytes = new Uint8Array(tile);
  const kept: Array<[number, number]> = [];
  let keptBytes = 0;
  let cursor = 0;
  while (cursor < bytes.length) {
    const start = cursor;
    const [tag, afterTag] = readVarint(bytes, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag & 7;
    cursor = skipField(bytes, wireType, afterTag);
    if (field !== 3 || wireType !== 2) continue;
    const [, bodyStart] = readVarint(bytes, afterTag);
    if (layerName(bytes, bodyStart, cursor) !== BUILDING_SOURCE_LAYER) continue;
    kept.push([start, cursor]);
    keptBytes += cursor - start;
  }
  if (keptBytes === bytes.length) return tile;
  const out = new Uint8Array(keptBytes);
  let offset = 0;
  for (const [start, end] of kept) {
    out.set(bytes.subarray(start, end), offset);
    offset += end - start;
  }
  return out.buffer;
};

// A fresh buffer every time: MapLibre transfers the data to its worker,
// which detaches it, so a shared empty buffer would only work once.
const emptyTile = () => ({ data: new ArrayBuffer(0) });

const fetchTile = async (url: string, signal: AbortSignal) => {
  const response = await fetch(url, { signal });
  if (response.status === 404 || response.status === 204) return null;
  if (!response.ok)
    throw new Error(`Building tile request failed: HTTP ${response.status}`);
  return response.arrayBuffer();
};

/**
 * Register the stitching protocol. `localBase` is the path the site is served
 * from ("/" or "/Kalamazoo-Goose/"), where public/buildings lives.
 */
export const registerBuildingTileProtocol = (
  maplibre: {
    addProtocol: (protocol: string, action: AddProtocolAction) => void;
    removeProtocol: (protocol: string) => void;
  },
  localBase: string,
) => {
  const loadTile: AddProtocolAction = async (params, abortController) => {
    const match = /tile\/(\d+)\/(\d+)\/(\d+)/.exec(params.url);
    if (!match) throw new Error(`Unexpected building tile URL ${params.url}`);
    const zoom = Number(match[1]);
    const x = Number(match[2]);
    const y = Number(match[3]);
    const signal = abortController.signal;
    if (inBuildingTileCoverage(zoom, x, y)) {
      const data = await fetchTile(
        `${localBase}buildings/${zoom}/${x}/${y}.pbf`,
        signal,
      );
      return data ? { data } : emptyTile();
    }
    if (!osmBuildingTileTemplate) return emptyTile();
    const url = osmBuildingTileTemplate
      .replace('{z}', String(zoom))
      .replace('{x}', String(x))
      .replace('{y}', String(y));
    const data = await fetchTile(url, signal);
    return data ? { data: extractBuildingLayer(data) } : emptyTile();
  };
  maplibre.removeProtocol(BUILDING_TILE_PROTOCOL);
  maplibre.addProtocol(BUILDING_TILE_PROTOCOL, loadTile);
};
