// Generated by scripts/build-building-tiles.mjs. Do not edit by hand.
//
// The zoom-14 tiles under public/buildings that carry the LiDAR-measured
// building heights. Tiles outside this range come from OpenFreeMap.
export const BUILDING_TILE_ZOOM = 14;
export const BUILDING_TILE_COVERAGE = {
  minX: 4293,
  maxX: 4297,
  minY: 6062,
  maxY: 6067,
} as const;
