export type ChaosSecretTrigger =
  | 'honk'
  | 'multi-honk'
  | 'water-honk'
  | 'touch'
  | 'air';

export type ChaosSecretEffect =
  | 'launch'
  | 'boost'
  | 'low-gravity'
  | 'mega-honk'
  | 'slippery'
  | 'spin'
  | 'stamina'
  | 'traffic-wobble';

export type ChaosSecretVisual =
  | 'honk-shrine'
  | 'air-gate'
  | 'bonk-cluster'
  | 'rideable'
  | 'prop-goal';

export type BonusChaosSecret = {
  readonly id: string;
  readonly label: string;
  readonly east: number;
  readonly north: number;
  readonly altitude: number;
  readonly radius: number;
  readonly trigger: ChaosSecretTrigger;
  readonly effect: ChaosSecretEffect;
  readonly requiredHonks: number;
  readonly points: number;
  readonly visual: ChaosSecretVisual;
  readonly color: number;
};

export const BONUS_CHAOS_SECRETS = [
  {
    id: 'kanley-bell',
    label: 'The Bell Tolls for Goose',
    east: 245,
    north: -225,
    altitude: 0.1,
    radius: 9,
    trigger: 'multi-honk',
    effect: 'launch',
    requiredHonks: 3,
    points: 500,
    visual: 'honk-shrine',
    color: 0xf4b942,
  },
  {
    id: 'library-shush',
    label: 'Extremely Loud Library Goose',
    east: 520,
    north: -75,
    altitude: 0.1,
    radius: 7,
    trigger: 'honk',
    effect: 'mega-honk',
    requiredHonks: 1,
    points: 400,
    visual: 'honk-shrine',
    color: 0xe8e2cf,
  },
  {
    id: 'student-megaphone',
    label: 'Unauthorized Announcement',
    east: 400,
    north: -210,
    altitude: 0.1,
    radius: 9,
    trigger: 'multi-honk',
    effect: 'mega-honk',
    requiredHonks: 5,
    points: 650,
    visual: 'honk-shrine',
    color: 0xff8f3d,
  },
  {
    id: 'meter-revolt',
    label: 'Parking Meter Uprising',
    east: -180,
    north: -180,
    altitude: 0.1,
    radius: 7,
    trigger: 'honk',
    effect: 'traffic-wobble',
    requiredHonks: 1,
    points: 450,
    visual: 'honk-shrine',
    color: 0x65d6b4,
  },
  {
    id: 'goose-choir',
    label: 'The Honkening Choir',
    east: -180,
    north: 410,
    altitude: 0.1,
    radius: 9,
    trigger: 'honk',
    effect: 'stamina',
    requiredHonks: 1,
    points: 550,
    visual: 'honk-shrine',
    color: 0xf6d365,
  },
  {
    id: 'waldo-field-goal',
    label: 'Illegal Touchdown',
    east: 690,
    north: -250,
    altitude: 14,
    radius: 5,
    trigger: 'air',
    effect: 'boost',
    requiredHonks: 0,
    points: 900,
    visual: 'air-gate',
    color: 0xf4b942,
  },
  {
    id: 'ramp-pinball',
    label: 'Parking Ramp Pinball',
    east: 130,
    north: -420,
    altitude: 12,
    radius: 5,
    trigger: 'air',
    effect: 'boost',
    requiredHonks: 0,
    points: 750,
    visual: 'air-gate',
    color: 0xff5f87,
  },
  {
    id: 'chemistry-wind',
    label: 'Experimental Tailwind',
    east: 610,
    north: 40,
    altitude: 30,
    radius: 6,
    trigger: 'air',
    effect: 'low-gravity',
    requiredHonks: 0,
    points: 800,
    visual: 'air-gate',
    color: 0x66e3ff,
  },
  {
    id: 'drone-swarm',
    label: "Birds Aren't Real",
    east: -20,
    north: -485,
    altitude: 24,
    radius: 7,
    trigger: 'air',
    effect: 'stamina',
    requiredHonks: 0,
    points: 700,
    visual: 'air-gate',
    color: 0x83f0c1,
  },
  {
    id: 'moon-cheese',
    label: 'Lunar Dairy Research',
    east: 820,
    north: 115,
    altitude: 42,
    radius: 4,
    trigger: 'touch',
    effect: 'low-gravity',
    requiredHonks: 0,
    points: 1_000,
    visual: 'air-gate',
    color: 0xffe36e,
  },
  {
    id: 'cone-crown',
    label: 'Supreme Cone Authority',
    east: 70,
    north: -205,
    altitude: 0.1,
    radius: 8,
    trigger: 'touch',
    effect: 'traffic-wobble',
    requiredHonks: 0,
    points: 500,
    visual: 'bonk-cluster',
    color: 0xff7a2f,
  },
  {
    id: 'bike-xylophone',
    label: 'Rack and Roll',
    east: 475,
    north: -285,
    altitude: 0.1,
    radius: 7,
    trigger: 'touch',
    effect: 'traffic-wobble',
    requiredHonks: 0,
    points: 650,
    visual: 'bonk-cluster',
    color: 0xb6c8d9,
  },
  {
    id: 'cafeteria-tray',
    label: 'Meal Plan Surfing',
    east: 395,
    north: -218,
    altitude: 0.08,
    radius: 3.5,
    trigger: 'touch',
    effect: 'slippery',
    requiredHonks: 0,
    points: 550,
    visual: 'rideable',
    color: 0xd8dde3,
  },
  {
    id: 'bronco-bucker',
    label: 'Unlicensed Bronco Rider',
    east: -60,
    north: 245,
    altitude: 0.1,
    radius: 3,
    trigger: 'touch',
    effect: 'spin',
    requiredHonks: 0,
    points: 700,
    visual: 'rideable',
    color: 0x7a4a26,
  },
  {
    id: 'dumpster-portal',
    label: 'Waste Management Major',
    east: -165,
    north: -720,
    altitude: 0.1,
    radius: 4,
    trigger: 'touch',
    effect: 'launch',
    requiredHonks: 0,
    points: 800,
    visual: 'rideable',
    color: 0x397553,
  },
  {
    id: 'lawson-puck',
    label: 'Puck Off',
    east: -25.5,
    north: -1008.5,
    altitude: 0.08,
    radius: 4,
    trigger: 'touch',
    effect: 'slippery',
    requiredHonks: 0,
    points: 900,
    visual: 'prop-goal',
    color: 0x20242a,
  },
  {
    id: 'university-hoop',
    label: 'Full-Court Goose',
    east: 758.6,
    north: -182,
    altitude: 11,
    radius: 4.5,
    trigger: 'air',
    effect: 'traffic-wobble',
    requiredHonks: 0,
    points: 1_000,
    visual: 'prop-goal',
    color: 0xf28c28,
  },
  {
    id: 'flamingo-dominoes',
    label: 'Lawn Ornament Extinction',
    east: -330,
    north: 85,
    altitude: 0.08,
    radius: 8,
    trigger: 'touch',
    effect: 'launch',
    requiredHonks: 0,
    points: 600,
    visual: 'bonk-cluster',
    color: 0xff75a8,
  },
  {
    id: 'acorn-offering',
    label: "Squirrel King's Tribute",
    east: 350,
    north: 255,
    altitude: 0.1,
    radius: 6,
    trigger: 'touch',
    effect: 'stamina',
    requiredHonks: 0,
    points: 750,
    visual: 'prop-goal',
    color: 0x9a6334,
  },
  {
    id: 'bench-catapult',
    label: 'Take a Seat, Lose a Seat',
    east: 300,
    north: 315,
    altitude: 0.08,
    radius: 3,
    trigger: 'honk',
    effect: 'launch',
    requiredHonks: 1,
    points: 650,
    visual: 'rideable',
    color: 0x6d4529,
  },
  {
    id: 'asylum-lake-leviathan',
    label: 'Asylum Lake Leviathan',
    east: -1_854,
    north: -2_053.8,
    altitude: 0.18,
    radius: 18,
    trigger: 'water-honk',
    effect: 'low-gravity',
    requiredHonks: 1,
    points: 1_200,
    visual: 'honk-shrine',
    color: 0x79d1bd,
  },
  {
    id: 'parkview-wind-tunnel',
    label: 'Parkview Wind Tunnel',
    east: -1_929.8,
    north: -3_495.5,
    altitude: 32,
    radius: 7,
    trigger: 'air',
    effect: 'boost',
    requiredHonks: 0,
    points: 1_400,
    visual: 'air-gate',
    color: 0xf1c500,
  },
  {
    id: 'library-after-hours',
    label: 'Overdue at The Library',
    east: -1_513.3,
    north: -887.2,
    altitude: 20,
    radius: 6,
    trigger: 'air',
    effect: 'mega-honk',
    requiredHonks: 0,
    points: 950,
    visual: 'air-gate',
    color: 0xe8e2cf,
  },
  {
    id: 'old-goat-simulator',
    label: 'The G.O.A.T. Simulator',
    east: -425.4,
    north: -424.4,
    altitude: 16,
    radius: 6,
    trigger: 'air',
    effect: 'spin',
    requiredHonks: 0,
    points: 900,
    visual: 'air-gate',
    color: 0x8d613f,
  },
  {
    id: 'fraternity-honkening',
    label: 'Rush Week Honkening',
    east: -878.6,
    north: -756.9,
    altitude: 0.12,
    radius: 12,
    trigger: 'multi-honk',
    effect: 'traffic-wobble',
    requiredHonks: 5,
    points: 1_100,
    visual: 'honk-shrine',
    color: 0xf1c500,
  },
  {
    id: 'bronson-goose-cannon',
    label: 'Bronson Goose Cannon',
    east: 2_608.3,
    north: 581,
    altitude: 0.08,
    radius: 4,
    trigger: 'touch',
    effect: 'launch',
    requiredHonks: 0,
    points: 1_300,
    visual: 'rideable',
    color: 0xd4a24c,
  },
  {
    id: 'usonian-flight',
    label: 'Usonian Fly-By',
    east: -1_192,
    north: -2_278.7,
    altitude: 18,
    radius: 6,
    trigger: 'air',
    effect: 'low-gravity',
    requiredHonks: 0,
    points: 1_200,
    visual: 'air-gate',
    color: 0xc78f52,
  },
] as const satisfies readonly BonusChaosSecret[];

export const TOTAL_CAMPUS_SECRETS = BONUS_CHAOS_SECRETS.length + 6;
