// Generated by scripts/lidar-trees/index.html. Do not edit by hand.
//
// The zoom-14 tiles under public/trees that carry LiDAR-detected tree
// positions. Inside this range the engine plants the measured trees;
// outside it falls back to the OpenStreetMap woodland and street-tree
// placement.
export const TREE_TILE_ZOOM = 14;
export const TREE_TILE_COVERAGE = {
  minX: 4293,
  maxX: 4297,
  minY: 6063,
  maxY: 6066,
} as const;

/**
 * Binary layout of one tree tile (little-endian):
 *
 *   bytes 0..3   ASCII "KGT1"
 *   bytes 4..7   uint32 tree count
 *   then, per tree, 12 bytes:
 *     int32  longitude * 1e7
 *     int32  latitude * 1e7
 *     uint8  height in 0.25 m units (canopy top above ground)
 *     uint8  crown radius in 0.25 m units
 *     uint8  crown fullness 0..255 (share of crown cells that returned
 *            points: a proxy for a dense conifer versus a bare-branched
 *            deciduous crown in the leaf-off flight)
 *     uint8  reserved, 0
 *
 * Trees are sorted tallest first within a tile.
 */
export const TREE_TILE_MAGIC = 'KGT1';
export const TREE_TILE_RECORD_BYTES = 12;
export const TREE_TILE_HEADER_BYTES = 8;
export const TREE_TILE_METRIC_UNIT = 0.25;
